
version: "2.1"

services:

  validator:
    privileged: true
    build: validatorN
    command: sh ./etc/sawtooth/validator.sh
  validator0:
    image: hyperledger/sawtooth-validator:latest
    container_name: validator0
    expose:
      - 4004
    ports:
      - "4004:4004"
      - "8800:8800"

    networks:
      app_net:
        ipv4_address: 172.16.239.14
    # start the validator with an empty genesis batch
    entrypoint: "bash -c \"\
        sawadm keygen && \
        sawtooth keygen my_key && \
        sawset genesis -k /root/.sawtooth/keys/my_key.priv && \
        sawadm genesis config-genesis.batch && \
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800 \
        \""
  validator1:
    extends: 
      service: validator
    container_name: validator1
    ports:
      - "4005:4004"
    depends_on:
      - validator0    
    networks:
      app_net:
        ipv4_address: 172.16.239.15

  validator2:
    extends: 
      service: validator
    container_name: validator2
    ports:
      - "4006:4004"
    depends_on:
      - validator0
    networks:
      app_net:
        ipv4_address: 172.16.239.16
  
networks: 
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.239.0/24 
 